### ISSUE TITLE
Life without ActiveSupport

### ISSUE THREAD

**Issue by ADone** [nov/rack-oauth2#52]
I've just removed ActiveSupport usage from rack-oauth2. Whether you are interested to merge it?

For proofs:
* less memory footprint
* no monkey patching and hidden surprises
* less dependencies

Last item is doubtful, because I added a two small dependencies for backward compatibility with removed functionality.

**Comment by ADone** [comment]
#53

**Comment by nov** [comment]
is core_ext so heavy for you?

**Comment by ADone** [comment]
Yes, it's heavy and slow. I'm not only one who think that ActiveSupport is full of great ideas, but with wrong realizations.
I just want a small rack-app, with zero or small dependencies. If I wanted to use components of or full rails framework, I would use a different gem, such as doorkeeper.

**Comment by nov** [comment]
hum, then specifying active_support features more strictedly then whole "active_support/core_ext" seems better for me.

**Comment by ADone** [comment]
Ok, I see. I close request.
