### ISSUE TITLE
Authorization endpoint returning token as URL fragment instead of query

### ISSUE THREAD

**Issue by RaoulDijksman** [nov/rack-oauth2#59]
Hey guys,

Every time i try to do an implicit flow i get the access token with an hashtag (#) in the redirect_uri:
`http://my.com/auth_callback#access_token=123abc`

This is becuase the method `protocol_params_location` in the class `Rack::OAuth2::Server::Authorize::Token::Response` returns `:fragment`. Changing it to `:query` fixes the problem and returns the token as a http query parameter (with a questionmark): 
`http://my.com/auth_callback?access_token=123abc`

I believe this to be a bug, am i correct in assuming this? If so I'm willing to make an PR.

Rack:OAuth2 version: 1.4
Rails version: 4.2.7
Ruby version: 2.3.1

**Comment by nov** [comment]
no it's intended

**Comment by RaoulDijksman** [comment]
Aaa oke! I see now, Thank you!
