### ISSUE TITLE
identifier used for both client_id and basic auth user

### ISSUE THREAD

**Issue by solipet** [nov/rack-oauth2#64]
I'm working on a project that is going to authenticate via openid_connect against `login.gov` (US government IDP).  For development, they provide a sandbox that is (mildly) protected via basic auth: `https://idp.int.login.gov/`  To hit their authorization endpoint, one must provide a previously registered `client_id` (see https://developers.login.gov/oidc/#authorization).

In `lib/rack/oauth2/client.rb:23`, the `client_id` is being overridden and set to `self.identifier`.  Later, on line 84, the same `identifier` is being used as the basic auth username.  As such we are unable to successfully use the IDP with any configuration.

We can get around this by simply commenting out line 23 and passing `client_id` as a param, and setting the client's `identifier` to the basic auth username.

Why is the identifier being used for both, seemingly different, purposes?  Commenting out the `client_id` override, all specs still pass so it's not clear why that is desired/required.

Any assistance/guidance you can provide would be greatly appreciated!

**Comment by nov** [comment]
line 23 is for authorization request.
line 84 is for token request.
both should include the same client identifier.

**Comment by solipet** [comment]
For the login.gov sandbox, the pre-registered `client_id` is a URN, but for basic auth, they use a simple, different, username.  Are you saying that we should reset the identifier in the client depending on which step we are on?

**Comment by nov** [comment]
This gem is designed for normal OAuth.
Your usecase isn’t normal.

So, current implementation isn’t supporting your case.

**Comment by solipet** [comment]
gotcha -- thanks anyway!

**Comment by nov** [comment]
Hi, I've added JWT Bearer as client authentication method.
So now you can specify it.

However, basic authentication header in your use-case is totally out of OAuth's scope, so you need handle it via `httpclient` layer.
`Rack::OAuth2.http_config(&block)` allows you to specify `httpclient` config (it's in global context though).

```ruby
require 'rack/oauth2'

Rack::OAuth2.debug!

Rack::OAuth2.http_config do |config|
  config.force_basic_auth = true
  config.set_auth('https://idp.int.login.gov/api/openid_connect/token', 'username', 'password')
end

client = Rack::OAuth2::Client.new(
  identifier: 'client_id',
  authorization_endpoint: 'https://idp.int.login.gov/openid_connect/authorize',
  token_endpoint: 'https://idp.int.login.gov/api/openid_connect/token',
  redirect_uri: 'https://client.example.com/callback'
)

client.access_token!(
  :jwt_bearer,
  client_assertion: 'jwt-assertion'
)
```

**Comment by nov** [comment]
@solipet 
Hi, I slightly improved the JWT bearer client assertion support.
Now you can specify `Rack::OAuth2::Client#private_key` (or `OpenIDConnect::Client#private_key` if you use openid_connect gem), and gem automatically generate JWT assertion for you.
https://gist.github.com/nov/98d26044e2f7c5b7d8fdba2b9bd101b4

Cheers

**Comment by solipet** [comment]
@nov thanks for the follow up -- we'll definitely take advantage of your JWT changes to clean up our code!
