### ISSUE TITLE
Support custom token types

### ISSUE THREAD

**Issue by wasifhossain** [nov/rack-oauth2#65]
Currently only `bearer`, `mac` or `nil` are supported as `:token_type`. It would be awesome to have support for custom values.

If we take **Ebay** for example, it mints 2 types of tokens: [`Application Access Token`](https://developer.ebay.com/api-docs/static/oauth-qref-client-credentials-grant.html) and [`User Access Token`](https://developer.ebay.com/api-docs/static/oauth-qref-auth-code-grant.html), which are set inside the `:token_type` in corresponding successful response.

As both of them are of basically `Bearer` token types, we can simply **add the regexp** in the `Rack::OAuth2::Client#handle_success_response` method on line [#148](https://github.com/nov/rack-oauth2/blob/master/lib/rack/oauth2/client.rb#L148) to support the case:

```
when /bearer|access token/
```

Do you think it should work?

Many Thanks!

**Comment by nov** [comment]
Does this work for you?
You can now "force" token type.

```ruby
client.force_token_type! :bearer
client.access_token!
```

**Comment by wasifhossain** [comment]
Ah I see! that's much cleaner solution. Thank you again for pointing that out!
