### ISSUE TITLE
Code based on rack-oauth2-sample Fails after version 1.12 of rack-oauth2.

### ISSUE THREAD

**Issue by tbtalbottjr** [nov/rack-oauth2#77]
I was updating an older app and found that I could not update beyond version 1.12 due to the requirement for rack >2.1.0. This breaks code that is based on the example code in https://github.com/nov/rack-oauth2-sample.  Specifically, it breaks in code based on app/controllers/authorizations_controller.rb:

    def respond(status, header, response)
      ["WWW-Authenticate"].each do |key|
        headers[key] = header[key] if header[key].present?
      end
      if response.redirect?
        redirect_to header['Location']
      else
        render :new
      end
    end

With:

`NoMethodError: undefined method 'redirect?' for []:Array`

I see that fixes have been made to the tests in 1.13.0.beta to account for the change in the return value from rack, but the sample code has not been updated to work with that version. 

From what I can tell, we now get less information since we don't actually get the response object anymore. What is the best way to rewrite this method so that it works as before?

**Comment by JosimarCamargo** [comment]
Hello, I'm facing the same issue, I would like to know if this is expected behavior?

I write a (really poor)test (when I raise an error if the response didn't match the expectation) I hope this help:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  ruby '2.5.1'
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.0.7.2"
  gem 'rack', '2.1.0'
  gem 'rack-oauth2', '1.16.0'
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  # Rack::OAuth2.debug!
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    my_auth = Rack::OAuth2::Server::Authorize.new do |req, res|
      res.code = 123
      res.redirect_uri = 'http://localhost:9292/callback'
      res.approve!
    end
    status, header, response = my_auth.call(request.env)
    raise StandardError, 'status should be 302' unless status == 302
    raise StandardError, 'response should have the redirect location filled' unless header['Location'] == 'http://localhost:9292/callback?code=123'
    raise StandardError, 'response should be a Rack::BodyProxy instance' unless response.class == Rack::BodyProxy
    raise StandardError, 'response should respond_to redirect?' unless response.respond_to?(:redirect?)

    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/?client_id=123&response_type=code"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end

```

**Comment by JosimarCamargo** [comment]
With rack `2.0.9` and rack-oauth2 `1.12.0` works fine

**Comment by kuzukuzu** [comment]
I encountered same issue with `rack 2.2.3` and `rack-oauth2 1.16.0`.

**Comment by tcannonfodder** [comment]
You can rebuild the `Rack::Response` with the following:

```ruby
def handle_oauth_response(status, header, body)
  ["WWW-Authenticate"].each do |key|
    headers[key] = header[key] if header[key].present?
  end
  response = ::Rack::Response.new(body, status, header)
  if response.redirect?
  ...
```
