### ISSUE TITLE
Need support for setting custom headers on token requests

### ISSUE THREAD

**Issue by jhollinger** [nov/rack-oauth2#79]
I'm integrating with an API that requires a custom header when requesting an Access Token (the `client_id` and `client_secret` params aren't enough for them, I guess). At present I don't see any way to accomplish this, but support _could_ be added with a simple patch.

Something like the following in `Rack::OAuth2::Client#access_token!`:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/81826/96922722-360a1f80-147e-11eb-9f27-af52af1fd2b8.png">

I'm happy to work on it, but wanted to ask if that was potentially acceptable, or if I'm missing an existing way to do it, before spending time on it.

**Comment by nov** [comment]
after v2.0.0, this gem uses faraday instead of httpclient.
and now you can modify request by passing block as below.

```ruby
client.access_token! do |request|
  request.headers['X-Foo'] = 'bar'
end
```
