### ISSUE TITLE
Add support for PKCE

### ISSUE THREAD

**Issue by jamietanna** [nov/rack-oauth2#83]
I was wondering if you would be interested in a PR to add PKCE support for Authorization Code Grants?

It's being adopted wider now, although [it's possible to use with this library](https://www.jvt.me/posts/2021/03/06/pkce-ruby-rack-oauth2/) it'd be great if it was a first class citizen.

**Comment by nov** [comment]
PKCE support for OAuth servers is here.
https://github.com/nov/rack-oauth2/blob/master/lib/rack/oauth2/server/extension/pkce.rb

I don't think PKCE-specific feature is needed for OAuth clients here.

**Comment by jamietanna** [comment]
Ah sorry yeah should've clarified I meant this was for a client.

Why do you feel we don't need support?

**Comment by nov** [comment]
You can add any params in authorization and token requests.

**Comment by jamietanna** [comment]
I was thinking, with PKCE becoming more widespread (ie its part of OAuth 2.1) we could make it something built in so its easier to use?

**Comment by nov** [comment]
If it's easier than this code, it's worth thinking.

```ruby
session[:code_verifier] = code_verifier = SecureRandom.hex(16)
client.authorization_uri(
  code_challenge_method: :S256,
  code_challenge: Util.urlsafe_base64_encode(
    OpenSSL::Digest::SHA256.digest(code_verifier)
  )
)
```

```ruby
client.authorization_code = params[:code]
client.access_token!(
  code_verifier: session[:code_verifier]
)
```

**Comment by jamietanna** [comment]
So PKCE should be backwards-compatible for Authorization Servers that don't support it, because they'll just reject the request, so I wonder if we should just be sending the parameters all the time?

**Comment by nov** [comment]
It's application's decision, not library's.
