### ISSUE TITLE
`client_id` should be optional for Access Token Request of Resource Owner Password Credentials Grant

### ISSUE THREAD

**Issue by vizv** [nov/rack-oauth2#88]
According to https://datatracker.ietf.org/doc/html/rfc6749#section-4.3.2, Access Token Request doesn't require `client_id` for `grant_type="password"`, not even optional, however

https://github.com/nov/rack-oauth2/blob/fe138af6e4c931e46b807ac8833d7d13d8631baa/lib/rack/oauth2/server/abstract/request.rb#L7

made `client_id` mandatory, and `Rack::OAuth2::Server::Token::Password` raises `AttrRequired::AttrMissing` error on call, and end-user sees
```json
{
    "error": "invalid_request",
    "error_description": "'client_id' required."
}
```

if `client_id` is not provided.

Maybe `attr_required :client_id` should be moved to other `Token` endpoint handlers where required?

**Comment by vizv** [comment]
For now I use the following patch to remove `:client_id` from required attribute list.
```ruby
module RackOAuth2Patch
  def self.prepended(base)
    base.instance_variable_get(:@required_attributes).delete(:client_id)
  end
end
Rack::OAuth2::Server::Token::Password::Request.prepend RackOAuth2Patch
```

**Comment by nov** [comment]
don't allow that flow for public clients.
